services:
  - type: web
    name: smyle-play
    runtime: python
    buildCommand: "echo 'No build needed'"
    startCommand: "python3 server.py"
    envVars:
      - key: PORT
        generateValue: false
